In [ ]:
pip install rdkit

In [ ]:
!git clone https://github.com/ChemFoundationModels/ChemLLMBench.git

fatal: destination path 'ChemLLMBench' already exists and is not an empty directory.


In [ ]:
import openai
import random
import pandas as pd
from tqdm import tqdm
import numpy as np
from sklearn.metrics import f1_score,accuracy_score
from rdkit import Chem
from rdkit.Chem.Scaffolds import MurckoScaffold
from rdkit.Chem import DataStructs
from rdkit.Chem import rdMolDescriptors
from rdkit import Chem
import warnings
from rdkit import RDLogger
# from steamship import Steamship
import datetime
import os
import time

In [ ]:
random.seed(42)
#read bace dataset
bace = pd.read_csv("/content/ChemLLMBench/data/property_prediction/BACE.csv")
bbbp = pd.read_csv("/content/ChemLLMBench/data/property_prediction/BBBP.csv")

In [ ]:
mkdir '/content/results/'

mkdir: cannot create directory ‘/content/results/’: File exists


In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import warnings

from sklearn.preprocessing import LabelEncoder
from sklearn.impute import KNNImputer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import f1_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score

In [ ]:
data1 = bace
data2 = bbbp

In [ ]:
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem, DataStructs

def smiles_to_morgan_fp(smiles, radius=2, n_bits=1024):
    """Return a 1D numpy array with a 1024-bit Morgan fingerprint."""
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    fp = AllChem.GetMorganFingerprintAsBitVect(mol, radius, nBits=n_bits)
    arr = np.zeros((n_bits,), dtype=int)
    DataStructs.ConvertToNumpyArray(fp, arr)
    return arr

# Apply to the whole column
fps = []
labels = []

for smi, cls in zip(data1["mol"], data1["Class"]):
    arr = smiles_to_morgan_fp(smi)
    if arr is not None:
        fps.append(arr)
        labels.append(cls)

X = np.vstack(fps)           # shape: (n_samples, 1024)
y = np.array(labels)         # shape: (n_samples,)
print(X.shape, y.shape)


[22:20:03] DEPRECATION WARNING: please use MorganGenerator
[22:20:03] DEPRECATION WARNING: please use MorganGenerator
[22:20:03] DEPRECATION WARNING: please use MorganGenerator
[22:20:03] DEPRECATION WARNING: please use MorganGenerator
[22:20:03] DEPRECATION WARNING: please use MorganGenerator
[22:20:03] DEPRECATION WARNING: please use MorganGenerator
[22:20:03] DEPRECATION WARNING: please use MorganGenerator
[22:20:03] DEPRECATION WARNING: please use MorganGenerator
[22:20:03] DEPRECATION WARNING: please use MorganGenerator
[22:20:03] DEPRECATION WARNING: please use MorganGenerator
[22:20:03] DEPRECATION WARNING: please use MorganGenerator
[22:20:03] DEPRECATION WARNING: please use MorganGenerator
[22:20:03] DEPRECATION WARNING: please use MorganGenerator
[22:20:03] DEPRECATION WARNING: please use MorganGenerator
[22:20:03] DEPRECATION WARNING: please use MorganGenerator
[22:20:03] DEPRECATION WARNING: please use MorganGenerator
[22:20:03] DEPRECATION WARNING: please use MorganGenerat

(1513, 1024) (1513,)


[22:20:04] DEPRECATION WARNING: please use MorganGenerator
[22:20:04] DEPRECATION WARNING: please use MorganGenerator
[22:20:04] DEPRECATION WARNING: please use MorganGenerator
[22:20:04] DEPRECATION WARNING: please use MorganGenerator
[22:20:04] DEPRECATION WARNING: please use MorganGenerator
[22:20:04] DEPRECATION WARNING: please use MorganGenerator
[22:20:04] DEPRECATION WARNING: please use MorganGenerator
[22:20:04] DEPRECATION WARNING: please use MorganGenerator
[22:20:04] DEPRECATION WARNING: please use MorganGenerator
[22:20:04] DEPRECATION WARNING: please use MorganGenerator
[22:20:04] DEPRECATION WARNING: please use MorganGenerator
[22:20:04] DEPRECATION WARNING: please use MorganGenerator
[22:20:04] DEPRECATION WARNING: please use MorganGenerator
[22:20:04] DEPRECATION WARNING: please use MorganGenerator
[22:20:04] DEPRECATION WARNING: please use MorganGenerator
[22:20:04] DEPRECATION WARNING: please use MorganGenerator
[22:20:04] DEPRECATION WARNING: please use MorganGenerat

In [ ]:
print(X)

[[0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 1]
 [1 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

clf = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("F1 score:", f1_score(y_test, y_pred))


Accuracy: 0.7986798679867987
F1 score: 0.7781818181818182


In [ ]:
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem, DataStructs

def smiles_to_morgan_fp(smiles, radius=2, n_bits=1024):
    """Return a 1D numpy array with a 1024-bit Morgan fingerprint."""
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    fp = AllChem.GetMorganFingerprintAsBitVect(mol, radius, nBits=n_bits)
    arr = np.zeros((n_bits,), dtype=int)
    DataStructs.ConvertToNumpyArray(fp, arr)
    return arr

# Apply to the whole column
fps = []
labels = []

for smi, cls in zip(data2["smiles"], data2["p_np"]):
    arr = smiles_to_morgan_fp(smi)
    if arr is not None:
        fps.append(arr)
        labels.append(cls)

X = np.vstack(fps)           # shape: (n_samples, 1024)
y = np.array(labels)         # shape: (n_samples,)
print(X.shape, y.shape)


[22:24:22] DEPRECATION WARNING: please use MorganGenerator
[22:24:22] DEPRECATION WARNING: please use MorganGenerator
[22:24:22] DEPRECATION WARNING: please use MorganGenerator
[22:24:22] DEPRECATION WARNING: please use MorganGenerator
[22:24:22] DEPRECATION WARNING: please use MorganGenerator
[22:24:22] DEPRECATION WARNING: please use MorganGenerator
[22:24:22] DEPRECATION WARNING: please use MorganGenerator
[22:24:22] DEPRECATION WARNING: please use MorganGenerator
[22:24:22] DEPRECATION WARNING: please use MorganGenerator
[22:24:22] DEPRECATION WARNING: please use MorganGenerator
[22:24:22] DEPRECATION WARNING: please use MorganGenerator
[22:24:22] DEPRECATION WARNING: please use MorganGenerator
[22:24:22] DEPRECATION WARNING: please use MorganGenerator
[22:24:22] DEPRECATION WARNING: please use MorganGenerator
[22:24:22] DEPRECATION WARNING: please use MorganGenerator
[22:24:22] DEPRECATION WARNING: please use MorganGenerator
[22:24:22] DEPRECATION WARNING: please use MorganGenerat

(2039, 1024) (2039,)


[22:24:23] DEPRECATION WARNING: please use MorganGenerator
[22:24:23] DEPRECATION WARNING: please use MorganGenerator
[22:24:23] DEPRECATION WARNING: please use MorganGenerator
[22:24:23] DEPRECATION WARNING: please use MorganGenerator
[22:24:23] DEPRECATION WARNING: please use MorganGenerator
[22:24:23] DEPRECATION WARNING: please use MorganGenerator
[22:24:23] DEPRECATION WARNING: please use MorganGenerator
[22:24:23] DEPRECATION WARNING: please use MorganGenerator
[22:24:23] DEPRECATION WARNING: please use MorganGenerator
[22:24:23] DEPRECATION WARNING: please use MorganGenerator
[22:24:23] DEPRECATION WARNING: please use MorganGenerator
[22:24:23] DEPRECATION WARNING: please use MorganGenerator
[22:24:23] DEPRECATION WARNING: please use MorganGenerator
[22:24:23] DEPRECATION WARNING: please use MorganGenerator
[22:24:23] DEPRECATION WARNING: please use MorganGenerator
[22:24:23] DEPRECATION WARNING: please use MorganGenerator
[22:24:23] DEPRECATION WARNING: please use MorganGenerat

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

clf = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("F1 score:", f1_score(y_test, y_pred))


Accuracy: 0.8946078431372549
F1 score: 0.9345509893455098
